services:

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml
    networks:
      - web

  suma:
    build: ./suma
    networks:
      - web

  resta:
    build: ./resta
    networks:
      - web

  multiplicacion:
    build: ./multiplicacion
    networks:
      - web

  division:
    build: ./division
    networks:
      - web

networks:
  web:
    driver: bridge