http:
  routers:
    router-usuarios:
      rule: "PathPrefix(`/usuarios`)"
      service: service-usuarios
      entryPoints:
        - web

    router-cursos:
      rule: "PathPrefix(`/cursos`)"
      service: service-cursos
      entryPoints:
        - web

  services:
    service-usuarios:
      loadBalancer:
        servers:
          - url: "http://usuarios:8000" 

    service-cursos:
      loadBalancer:
        servers:
          - url: "http://cursos:8000"   