http:
  routers:
    router-suma:
      rule: "PathPrefix(`/suma`)"
      service: service-suma
      entryPoints:
        - web

    router-resta:
      rule: "PathPrefix(`/resta`)"
      service: service-resta
      entryPoints:
        - web

    router-multiplicacion:
      rule: "PathPrefix(`/multiplicacion`)"
      service: service-multiplicacion
      entryPoints:
        - web

    router-division:
      rule: "PathPrefix(`/division`)"
      service: service-division
      entryPoints:
        - web

  services:
    service-suma:
      loadBalancer:
        servers:
          - url: "http://suma:8001"

    service-resta:
      loadBalancer:
        servers:
          - url: "http://resta:8002"

    service-multiplicacion:
      loadBalancer:
        servers:
          - url: "http://multiplicacion:8003"

    service-division:
      loadBalancer:
        servers:
          - url: "http://division:8004"